services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/usr/src/app

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db

  db:
    image: mysql:8.0
    # restart: always  #開発環境のため、すぐに停止できるように。
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: django_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: